import { pgTable, text, timestamp, boolean, integer, jsonb, uuid } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: text("email").notNull().unique(),
  username: text("username").unique(),
  passwordHash: text("password_hash"),
  displayName: text("display_name"),
  avatarUrl: text("avatar_url"),
  bio: text("bio"),
  coverUrl: text("cover_url"),
  timezone: text("timezone"),
  displayEmail: boolean("display_email").default(false).notNull(),
  instagramUrl: text("instagram_url"),
  linkedinUrl: text("linkedin_url"),
  twitterUrl: text("twitter_url"),
  customLinks: jsonb("custom_links").default("[]"),
  location: text("location"),
  statusMessage: text("status_message"),
  skills: jsonb("skills").default("[]"),
  badges: jsonb("badges").default("[]"),
  stats: jsonb("stats").default("{}"),
  profileApps: jsonb("profile_apps").default("[]"),
  balance: integer("balance").default(600).notNull(),
  subscriptionTier: text("subscription_tier").default("free").notNull(),
  subscriptionExpiresAt: timestamp("subscription_expires_at"),
  isVerified: boolean("is_verified").default(true).notNull(),
  verificationCode: text("verification_code"),
  role: text("role").default("SUBACCOUNT_USER"),
  agencyId: uuid("agency_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const creatorAccounts = pgTable("creator_connected_accounts", {
  id: text("id").primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  platform: text("platform").notNull(),
  platformUserId: text("platform_user_id").notNull(),
  platformUsername: text("platform_username").notNull(),
  accessTokenEncrypted: text("access_token_encrypted").notNull(),
  refreshTokenEncrypted: text("refresh_token_encrypted"),
  tokenExpiresAt: timestamp("token_expires_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const creatorAutomationSettings = pgTable("creator_automation_settings", {
  id: text("id").primaryKey(),
  userId: uuid("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }),
  autoPublish: boolean("auto_publish").default(false).notNull(),
  manualApproval: boolean("manual_approval").default(true).notNull(),
  maxClipsPerStream: integer("max_clips_per_stream").default(3).notNull(),
  minClipScore: integer("min_clip_score").default(70).notNull(),
  language: text("language").default("en").notNull(),
  captionStyle: text("caption_style").default("modern_bold").notNull(),
  uploadPrivacy: text("upload_privacy").default("unlisted").notNull(),
  bannedTopics: jsonb("banned_topics").$type<string[]>().default([]),
  sourceType: text("source_type").default("own").notNull(),
  targetChannelUrl: text("target_channel_url"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const creatorStreams = pgTable("creator_streams", {
  id: text("id").primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  platform: text("platform").notNull(),
  externalStreamId: text("external_stream_id").notNull(),
  title: text("title"),
  status: text("status").notNull().default("detected_live"),
  vodUrl: text("vod_url"),
  durationSeconds: integer("duration_seconds"),
  startedAt: timestamp("started_at"),
  endedAt: timestamp("ended_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const creatorClips = pgTable("creator_clips", {
  id: text("id").primaryKey(),
  streamId: text("stream_id").notNull().references(() => creatorStreams.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  hookText: text("hook_text"),
  description: text("description"),
  hashtags: jsonb("hashtags").$type<string[]>().default([]),
  startTime: integer("start_time").notNull(),
  endTime: integer("end_time").notNull(),
  score: integer("score").notNull(),
  contentType: text("content_type").notNull(),
  videoUrl: text("video_url"),
  thumbnailUrl: text("thumbnail_url"),
  status: text("status").notNull().default("generated"),
  riskFlags: jsonb("risk_flags").$type<string[]>().default([]),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const creatorProcessingLogs = pgTable("creator_processing_logs", {
  id: text("id").primaryKey(),
  streamId: text("stream_id").notNull().references(() => creatorStreams.id, { onDelete: "cascade" }),
  level: text("level").notNull().default("info"),
  message: text("message").notNull(),
  meta: jsonb("meta"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
