'use server'

import { db } from '~/lib/visual-editor/db'
import { v4 } from 'uuid'
import { veFunnels, veFunnelPages } from '~/lib/db/schema'
import { parseHtmlToEditorElements } from './html-parser'

export type AIPage = {
  name: string
  pathName: string
  htmlContent: string
}

export async function publishAIToFunnel(chatId: string, subAccountId: string, pages: AIPage[]) {
  const funnelId = v4()
  await db.insert(veFunnels).values({
    id: funnelId,
    name: `AI Site - ${chatId.substring(0, 8)}`,
    description: 'Generated by AI Website Builder',
    subAccountId: subAccountId,
    subDomainName: `site-${funnelId.substring(0, 8)}`,
    liveProducts: '[]',
  })

  const insertedPages = []

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i]

    const parsedElements = parseHtmlToEditorElements(page.htmlContent)

    const pageContentJson = JSON.stringify([
      {
        content: parsedElements,
        id: '__body',
        name: 'Body',
        styles: {
          backgroundColor: 'white'
        },
        type: '__body'
      }
    ])

    const pageId = v4()
    await db.insert(veFunnelPages).values({
      id: pageId,
      name: page.name,
      pathName: page.pathName,
      funnelId: funnelId,
      order: i,
      content: pageContentJson,
    })

    insertedPages.push(pageId)
  }
  return { funnelId, pageId: insertedPages[0] }
}


