'use client';
import React from 'react';
import { classNames } from '~/utils/classNames';
import { Card } from '~/components/ui/Card';
import { Button } from '~/components/ui/Button';
import { Badge } from '~/components/ui/Badge';
import type { DbTable, TableData } from './types';

interface TablesTabProps {
  sqlMigrationFiles: [string, any][];
  dbTables: DbTable[];
  selectedTable: string | null;
  tableData: TableData | null;
  isPushing: boolean;
  onPushMigrations: () => void;
  onSelectTable: (name: string) => void;
  onBack: () => void;
}

const SCHEMA_BADGE: Record<string, { variant: any; label: string }> = {
  public: { variant: 'info', label: 'public' },
  auth: { variant: 'primary', label: 'auth' },
  storage: { variant: 'warning', label: 'storage' },
};

export function TablesTab({
  sqlMigrationFiles,
  dbTables,
  selectedTable,
  tableData,
  isPushing,
  onPushMigrations,
  onSelectTable,
  onBack,
}: TablesTabProps) {
  return (
    <div className="p-8 space-y-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">
            {selectedTable ? `→ ${selectedTable}` : 'Tables'}
          </h1>
          <p className="text-sm text-falbor-elements-textSecondary mt-0.5">
            {selectedTable ? 'Viewing live table data' : 'Browse all schemas and tables'}
          </p>
        </div>
        {selectedTable && (
          <Button variant="outline" size="sm" onClick={onBack}>
            ← Back
          </Button>
        )}
      </div>

      {!selectedTable ? (
        <>
          <Card className="border-falbor-elements-borderColor">
            <div className="flex items-center justify-between px-5 py-4 border-b border-falbor-elements-borderColor">
              <div>
                <h2 className="font-semibold text-sm">SQL Migrations ({sqlMigrationFiles.length})</h2>
                <p className="text-xs text-falbor-elements-textSecondary mt-0.5">
                  Push schema changes generated by the AI
                </p>
              </div>
              <Button
                onClick={onPushMigrations}
                disabled={isPushing || sqlMigrationFiles.length === 0}
                className="bg-[#3ECF8E] text-white hover:bg-[#35c07f] text-sm"
              >
                <div
                  className={classNames(
                    'w-4 h-4 mr-2',
                    isPushing ? 'i-ph:spinner-gap-bold animate-spin' : 'i-ph:upload-simple-bold',
                  )}
                />
                {isPushing ? 'Pushing...' : 'Push All'}
              </Button>
            </div>
            {sqlMigrationFiles.length > 0 ? (
              <div className="divide-y divide-falbor-elements-borderColor max-h-48 overflow-y-auto">
                {sqlMigrationFiles.map(([path]) => (
                  <div key={path} className="flex items-center gap-3 px-5 py-3 text-sm">
                    <div className="i-ph:file-sql text-[#3ECF8E] text-base flex-shrink-0" />
                    <span className="font-mono text-falbor-elements-textPrimary truncate">
                      {path.split('/').pop()}
                    </span>
                    <span className="ml-auto text-[10px] text-falbor-elements-textTertiary">
                      {path.split('/').slice(0, -1).join('/')}
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="px-5 py-6 text-sm text-falbor-elements-textTertiary italic text-center">
                No SQL migrations yet. Ask the AI to create your database schema.
              </p>
            )}
          </Card>

          {(['public', 'auth', 'storage'] as const).map((schema) => {
            const schemaTables = dbTables.filter((t) => t.schema === schema);
            if (!schemaTables.length) return null;
            const badge = SCHEMA_BADGE[schema] ?? { variant: 'default', label: schema };
            return (
              <Card key={schema} className="border-falbor-elements-borderColor">
                <div className="px-5 py-3 border-b border-falbor-elements-borderColor bg-falbor-elements-background-depth-2 flex items-center gap-3">
                  <Badge variant={badge.variant} size="md">
                    {badge.label}
                  </Badge>
                  <span className="text-xs text-falbor-elements-textTertiary">
                    {schemaTables.length} table{schemaTables.length !== 1 ? 's' : ''}
                  </span>
                </div>
                <div className="divide-y divide-falbor-elements-borderColor">
                  {schemaTables.map((t) => (
                    <div
                      key={t.fullName}
                      onClick={() => onSelectTable(t.fullName)}
                      className="flex items-center justify-between gap-3 px-5 py-3 text-sm hover:bg-falbor-elements-background-depth-2 cursor-pointer group transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <div className="i-ph:table text-falbor-elements-textTertiary group-hover:text-[#3ECF8E] text-base" />
                        <span className="font-medium">{t.name}</span>
                      </div>
                      <div className="i-ph:caret-right text-falbor-elements-textTertiary text-sm" />
                    </div>
                  ))}
                </div>
              </Card>
            );
          })}
        </>
      ) : (
        <Card className="border-falbor-elements-borderColor overflow-hidden">
          <div className="overflow-x-auto">
            {tableData ? (
              <table className="w-full text-sm text-left">
                <thead className="bg-falbor-elements-background-depth-2 border-b border-falbor-elements-borderColor">
                  <tr>
                    {tableData.columns.map((c) => (
                      <th
                        key={c}
                        className="px-5 py-3 text-xs font-semibold uppercase tracking-wider text-falbor-elements-textSecondary whitespace-nowrap"
                      >
                        {c}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {tableData.rows.length > 0 ? (
                    tableData.rows.map((row, i) => (
                      <tr
                        key={i}
                        className="border-b border-falbor-elements-borderColor hover:bg-falbor-elements-background-depth-2"
                      >
                        {tableData.columns.map((c) => (
                          <td
                            key={c}
                            className="px-5 py-3 max-w-[240px] truncate text-falbor-elements-textSecondary"
                            title={String(row[c])}
                          >
                            {String(row[c] ?? 'NULL')}
                          </td>
                        ))}
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td
                        colSpan={tableData.columns.length}
                        className="px-5 py-8 text-center text-falbor-elements-textTertiary italic"
                      >
                        This table is empty.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            ) : (
              <div className="p-8 text-center text-falbor-elements-textTertiary">
                <div className="i-ph:spinner-gap-bold animate-spin text-2xl mx-auto mb-2" />
                Loading data...
              </div>
            )}
          </div>
        </Card>
      )}
    </div>
  );
}
